#!/usr/bin/env python3
"""Generate every redirect artefact from migration/inventory.csv.

One CSV is the single source of truth, so the three redirect layers described in
the design document cannot disagree:

  1. path aliases      - not produced here; Hugo `aliases:` front matter handles
                         the few path-based old URLs (uploads). The old site has
                         no pretty permalinks, so this layer is nearly empty.
  2. query-string shim - static/redirects.json, read by the inline script in
                         layouts/_partials/redirect-shim.html. Works on any host,
                         including GitHub Pages.
  3. server 301s       - static/_redirects (Cloudflare path rules) and
                         static/nginx-redirects.conf (map $arg_page_id).

Query-string URLs (?page_id=N, ?p=N) cannot be served by path aliases: a static
host ignores the query string, so every such URL lands on the home page. Never
put a `?` URL in Hugo `aliases:`; it creates an unreachable directory literally
named "?page_id=N".
"""
import csv, json, pathlib, sys
from urllib.parse import urlsplit, parse_qs

ROOT = pathlib.Path(__file__).resolve().parent.parent
INVENTORY = ROOT / 'migration' / 'inventory.csv'
STATIC = ROOT / 'static'


def load():
    if not INVENTORY.exists():
        sys.exit(f'missing {INVENTORY}')
    rows = list(csv.DictReader(INVENTORY.open()))
    bad = [r for r in rows if not r['outcome']]
    if bad:
        sys.exit(f'{len(bad)} inventory rows have no outcome; assign them first')
    return rows


def main():
    rows = load()
    query_map, path_rules, skipped = {}, [], []

    for r in rows:
        target = r['target_path'].strip()
        if not target:
            # Already 404 before the migration: the design document's rule only
            # covers URLs that returned 200, so these get no rule.
            skipped.append(r['old_url'])
            continue
        parts = urlsplit(r['old_url'])
        q = parse_qs(parts.query)
        if 'page_id' in q:
            query_map[f"page_id={q['page_id'][0]}"] = target
        elif 'p' in q:
            query_map[f"p={q['p'][0]}"] = target
        elif parts.path and parts.path != '/':
            path_rules.append((parts.path, target))

    STATIC.mkdir(exist_ok=True)

    payload = json.dumps(query_map, indent=2, sort_keys=True) + '\n'
    (STATIC / 'redirects.json').write_text(payload)
    # assets/ copy is what the shim partial inlines at build time
    (ROOT / 'assets' / 'redirects.json').write_text(payload)

    # Cloudflare Pages _redirects: path rules only. Its syntax does not match
    # query strings, so page_id rules must be Redirect Rules on the zone.
    lines = ['# Generated by scripts/build_redirects.py. Do not edit.',
             '# Path-based rules only; query-string rules are in nginx-redirects.conf',
             '# and in static/redirects.json for the client-side shim.']
    lines += [f'{src}  {dst}  301' for src, dst in sorted(path_rules)]
    (STATIC / '_redirects').write_text('\n'.join(lines) + '\n')

    # nginx: true 301s for the query-string forms, for the VPS option.
    conf = ['# Generated by scripts/build_redirects.py. Do not edit.',
            'map $arg_page_id $re_page_redirect {',
            '    default "";']
    for k, v in sorted(query_map.items()):
        if k.startswith('page_id='):
            conf.append(f'    {k.split("=", 1)[1]:>6}  {v};')
    conf += ['}', '', 'map $arg_p $re_post_redirect {', '    default "";']
    for k, v in sorted(query_map.items()):
        if k.startswith('p='):
            conf.append(f'    {k.split("=", 1)[1]:>6}  {v};')
    conf += ['}', '',
             '# In the server block:',
             '#   if ($re_page_redirect) { return 301 $re_page_redirect; }',
             '#   if ($re_post_redirect) { return 301 $re_post_redirect; }']
    (STATIC / 'nginx-redirects.conf').write_text('\n'.join(conf) + '\n')

    print(f'redirects.json       {len(query_map):3d} query-string rules')
    print(f'_redirects           {len(path_rules):3d} path rules')
    print(f'nginx-redirects.conf {len(query_map):3d} rules')
    print(f'no rule (404 before) {len(skipped):3d}')


if __name__ == '__main__':
    main()
